grfplugin:
  eventListenerNodePort: 30081
  logPath: /var/log/grfplugin_logs
  rootServiceUUID:
  username: admin
  password: "AQ6h8PB8OVW7rBXHbDg75ic4ZP7cKIWgNHZZ41Qb4DwvZQ8Q-KEl0Fe26ddo_DLrs7MkLcNDplREwxlLOPvgFg=="
  lbHost:
  lbPort:
