urplugin:
  urPluginRootServiceUUID:
  username: admin
  password: AQ6h8PB8OVW7rBXHbDg75ic4ZP7cKIWgNHZZ41Qb4DwvZQ8Q-KEl0Fe26ddo_DLrs7MkLcNDplREwxlLOPvgFg==
  odimUsername: admin
  odimPassword:
  logPath: /var/log/urplugin_logs
